### ISSUE TITLE
Sprout sometimes fails to establish a connection with SNMPd

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/clearwater-net-snmp#10]
#### Symptoms
Sprout tries to connect to SNMPd (via the unix domain socket at `/var/agentx/master`) during startup, and SNMPd accepts the connection and then Sprout immediately receives a SIGPIPE.

I've started both SNMPd and Sprout under strace and I think the key bit is the following from
[snmpd-strace.txt](https://github.com/Metaswitch/clearwater-net-snmp/files/690198/snmpd-strace.txt):

```
15:01:02.369028 select(22, [4 6 7 9 11 12 13 14 15 16 17 18 19 20 21], [], [], {2, 758916}) = 1 (in [20], left {2, 698858})
15:01:02.429149 accept(20, {sa_family=AF_LOCAL, NULL}, [2]) = 35
15:01:02.429187 getsockopt(35, SOL_SOCKET, SO_SNDBUF, [212992], [4]) = 0
15:01:02.429212 getsockopt(35, SOL_SOCKET, SO_RCVBUF, [212992], [4]) = 0
15:01:02.429255 select(36, [3 4 6 7 9 11 12 13 14 15 16 17 18 19 20 21], [], [], {2, 698667}) = 1 (in [3], left {2, 698664})
15:01:02.429294 getsockname(35, {sa_family=AF_LOCAL, sun_path="/var/agentx/master"}, [21]) = 0
15:01:02.429321 recvfrom(35, 0xcf6720, 65536, 64, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
15:01:02.429410 close(35)
```

The timestamps correspond with Sprout trying to connect to SNMPd (c.f. with the bottom of 
[sprout-strace.txt](https://github.com/Metaswitch/clearwater-net-snmp/files/690199/sprout-strace.txt)). This snippet seems to show SNMPd:
* Accepting the connection (the first select and accept calls)
* Calling select on a group of sockets(3 4 6 7 9 11 12 13 14 15 16 17 18 19 20 21) that doesn't include the new connection socket (35)
* Being told that socket 3 is ready to be read from
* Calling recvfrom on socket 35, which isn't ready to be read from, which causes SNMPd to close the connection.

This causes a SIGPIPE to get sent to Sprout when it tries to write to the socket after the connection has been closed.

The second call to select just looks like it has the wrong arguments. It's possible that we always do the wrong call to select here and we often get away with it because we expect Sprout to have sent something (and therefore there will be something to read at the connection socket), although that seems unlikely.

#### Impact
Sprout won't start up (whilst SNMPd is running) on nodes that hit this problem.

#### Release and environment 
I can only reproduce this is on one split network (both IPv4) Sprout node (our VMware rig Sprout). It initially seemed to be reliably reproducible on this node, but actually it now seems to be intermittent.

net-snmp Version: 5.7.2~dfsg-clearwater5

#### Steps to reproduce
I've been running the following to repro, but as mentioned above, I have only reproduced this on one node, and even then it's not completely reliable.
* `sudo service clearwater-monit stop`
* `sudo service sprout stop`
* `sudo service snmpd stop`
* `sudo service snmpd start`
* `sudo service sprout start`  ----> Sprout fails to start (although it fails silently due to https://github.com/Metaswitch/clearwater-net-snmp/issues/11)

(You almost certainly don't even need to restart snmpd).

**Comment by graemerobertson** [comment]
Since this is intermittent and I have no idea what causes it, and since the symptoms once we hit it are clearly critical, I'm raising this to critical.

**Comment by rkd-msw** [comment]
https://github.com/Metaswitch/clearwater-net-snmp/blob/master/snmplib/snmp_api.c#L5524 might be relevant:

* it looks like the code around stream-based transports (which a UNIX domain socket is) isn't very robust
* I think that's the function which accepts a connection then tries to recvfrom() it without checking if it's readable

**Comment by mirw** [comment]
I've found the issue.  It was introduced by https://github.com/Metaswitch/clearwater-net-snmp/pull/8.

It's pretty subtle - basically, FD_SET, FD_CLR, FD_ISSET alias any file descriptors to ignore the 6th bit, i.e. it treats 3 the same as 35.  Hence, on this particular system (where we have the right number of connections), file descriptor 35 (which ends up being Sprout) aliases to 3 (which seems to almost always be readable).

The fix is to make sure gcc is using 64-bit long integers everywhere (if it's using 64-bit integers at all).

**Comment by mirw** [comment]
Once we've reviewed and tested this, we should push this fix upstream.  We should probably also bear in mind that un-applied patches are high risk and make sure we do sufficient testing of them.

**Comment by mirw** [comment]
OK, I've found that the official net-snmp code now has a different (and better) fix, so I'm going to take that instead - so no need to push upstream.

**Comment by mirw** [comment]
I believe this is now fixed.  @rkd-msw, please can you look out for any repeats of this during your testing, but I'm closing the issue now.
